spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/TheHien/Module4_Session7_Subject4/medical-config-repo
          search-paths: medical-config-repo
          default-label: main
server:
  port: 8888
